### PR TITLE
Blender29

### PR DESCRIPTION
**Pull request by kreezii**
- Get Datafiles path instead of binary blender path to avoid permissions problems, at least in some linux distros. bpy.utils.user_resource("DATAFILES") instead of os.path.dirname(bpy.app.binary_path)

- Fix some DragonBones export issues, bpy.ops.ed.undo() crashes blender after export, added bpy.ops.ed.undo_push to solve it.

- Update apply modifier for Blender 2.9  bpy.ops.object.modifier_apply() # for Blender 2.9X

### CODE REVIEW

**Comment by davord45** [comment]
Does this work with Blender 2.91?

**Comment by k4y4k** [comment]
Howdy :wave:

Installing this on Blender 2.90 seemed to work OK - haven't gotten around to DB export yet.

**But:** 2.91 does an odd insta-quit of any COA operation, spitting out a warning that says Tool `'coa_tools.draw_polygon' not found for space 'VIEW_3D'.`

**Comment by k4y4k** [comment]
Now it's all good! Thank you! :smile: :sparkles:

**Comment by ndee85** [comment]
I have fixed this slightly different. Checking previous version to make the addon compatible with older 2.9 versions.
Though thanks for the pull request!

**Pull request closed without merging**
