### PR TITLE
Update README.md to Blender 2.8, and clarify the steps.

### PR DESCRIPTION
**Pull request by rubenlg**
I had to fish all the information to make it work from various bugs, so I decided to update the README.md so others don't have to.

### CODE REVIEW

**Comment by rubenlg** [comment]
Hey @ndee85, could you approve this PR if it looks reasonable?

Thank you!

**Comment by LawrenceP4** [comment]
rubenlg thank you so much. I've spent hours downloading, installing, uninstalling, reinstalling, etc... trying to get this thing to work. Finally got it to install on Blender 2.83.16. For anyone else who's struggling, 2.83.16 is the LTS version on Blenders website. As for the installation process when you click on the install button you don't actually then select the "coa tools" folder. You actually close out blender during that window and then come back and type coa to find it suddenly there. Weird I know, but hey as long as it works

**Comment by rubenlg** [comment]
@ndee85 gentle ping...

**Comment by ndee85** [comment]
Thanks for the updated readme. Just merged. I have to admit, that I cannot commit much time into developement lately.
Need to push the 2.8 branch into master and create an extra 2.79 branch. I think this will make the it more obvious for people.

Are there any obvious showstopper with blender 2.93.x right now? Not worked for a longer time with coa tools.

**Comment by rubenlg** [comment]
Thanks a lot!

I don't use blender 2.9 yet, so I don't know what's broken at the moment. If I migrate my projects to 2.9 I'll have to look into it :)

**Pull request merged**
